"""empty message

Revision ID: e66be29cbd54
Revises: 356ea97f15e1
Create Date: 2022-11-05 03:14:02.827177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66be29cbd54'
down_revision = '356ea97f15e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
